### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by jashlength**
Brought a branch back from the graveyard. out of mana. needss to be checked before we merge it okayy.

### CODE REVIEW

**Comment by angusjlowe** [comment]
What are you on about mate??

**Comment by angusjlowe** [comment]
Also on a serious note why is a lot of stuff on the front-end deleted??

**Comment by jashlength** [comment]
Hmm. Something about a ton of red in the app files made me think we should
check it before we merge the new server code into master.

On Friday, July 15, 2016, Angus Lowe <notifications@github.com> wrote:

> What are you on about mate??
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angusjlowe/dpnm-2016/pull/31#issuecomment-232692196>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ13zSNNc-FtWE3meIesNMnJWl804ERdks5qVk_CgaJpZM4JMgXo>
> .
>


-- 
Senior in Mathematics
College of Science and Engineering,
University of Minnesota

**Comment by spark184** [comment]
Should I make my own branch and push my code? (idk if that's a thing or not)

**Comment by jashlength** [comment]
I genuinely don't know.  It should just be server code on there.  Which is
why we need to look it over in the morning and if all else fails, have me
make a new branch and push.
On Friday, July 15, 2016, Joseph Pate <patex019@umn.edu> wrote:

> Hmm. Something about a ton of red in the app files made me think we should
> check it before we merge the new server code into master.
>
> On Friday, July 15, 2016, Angus Lowe <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> What are you on about mate??
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/angusjlowe/dpnm-2016/pull/31#issuecomment-232692196>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AJ13zSNNc-FtWE3meIesNMnJWl804ERdks5qVk_CgaJpZM4JMgXo>
>> .
>>
>
>
> --
> Senior in Mathematics
> College of Science and Engineering,
> University of Minnesota
>
>

-- 
Senior in Mathematics
College of Science and Engineering,
University of Minnesota

**Comment by angusjlowe** [comment]
no one press the really big green button that looks ok to press

**Comment by spark184** [comment]
I have no idea what's going on, so I'll just wait until tomorrow morning;
unless you guys want them right now

**Comment by jashlength** [comment]
Right.  You don't need to make another branch sungjin. Everything should be
fine there. It's just with mine.

On Friday, July 15, 2016, Angus Lowe <notifications@github.com> wrote:

> no one press the really big green button that looks ok to press
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angusjlowe/dpnm-2016/pull/31#issuecomment-232696276>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ13zWdayrKcyJL-4AeLgZquPTmLatHeks5qVlL7gaJpZM4JMgXo>
> .
>


-- 
Senior in Mathematics
College of Science and Engineering,
University of Minnesota

**Comment by jashlength** [comment]
So basically no one fucking merge my pull request.  I probably fucked up.

On Friday, July 15, 2016, spark184 <notifications@github.com> wrote:

> I have no idea what's going on, so I'll just wait until tomorrow morning;
> unless you guys want them right now
>
> On Thu, Jul 14, 2016 at 10:17 AM, Angus Lowe <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > no one press the really big green button that looks ok to press
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/angusjlowe/dpnm-2016/pull/31#issuecomment-232696276
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ATIVqa4DSq-6tRJg17lw2afUEebOSvRvks5qVlL7gaJpZM4JMgXo
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angusjlowe/dpnm-2016/pull/31#issuecomment-232696561>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ13zQpPtv854Al2KbZTzl9eYF-wMw7zks5qVlM3gaJpZM4JMgXo>
> .
>


-- 
Senior in Mathematics
College of Science and Engineering,
University of Minnesota

**Pull request closed without merging**
